# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/Requests/UnknownPtr8Request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Networking/Platform/Requests/UnknownPtr8Request.proto',
  package='POGOProtos.Networking.Platform.Requests',
  syntax='proto3',
  serialized_pb=_b('\n@POGOProtos/Networking/Platform/Requests/UnknownPtr8Request.proto\x12\'POGOProtos.Networking.Platform.Requests\"%\n\x12UnknownPtr8Request\x12\x0f\n\x07message\x18\x01 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_UNKNOWNPTR8REQUEST = _descriptor.Descriptor(
  name='UnknownPtr8Request',
  full_name='POGOProtos.Networking.Platform.Requests.UnknownPtr8Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='POGOProtos.Networking.Platform.Requests.UnknownPtr8Request.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=146,
)

DESCRIPTOR.message_types_by_name['UnknownPtr8Request'] = _UNKNOWNPTR8REQUEST

UnknownPtr8Request = _reflection.GeneratedProtocolMessageType('UnknownPtr8Request', (_message.Message,), dict(
  DESCRIPTOR = _UNKNOWNPTR8REQUEST,
  __module__ = 'POGOProtos.Networking.Platform.Requests.UnknownPtr8Request_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Platform.Requests.UnknownPtr8Request)
  ))
_sym_db.RegisterMessage(UnknownPtr8Request)


# @@protoc_insertion_point(module_scope)
