# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Inventory/InventoryKey.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from POGOProtos.Enums import QuestType_pb2 as POGOProtos_dot_Enums_dot_QuestType__pb2
from POGOProtos.Enums import PokemonFamilyId_pb2 as POGOProtos_dot_Enums_dot_PokemonFamilyId__pb2
from POGOProtos.Inventory.Item import ItemId_pb2 as POGOProtos_dot_Inventory_dot_Item_dot_ItemId__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Inventory/InventoryKey.proto',
  package='POGOProtos.Inventory',
  syntax='proto3',
  serialized_pb=_b('\n\'POGOProtos/Inventory/InventoryKey.proto\x12\x14POGOProtos.Inventory\x1a POGOProtos/Enums/QuestType.proto\x1a&POGOProtos/Enums/PokemonFamilyId.proto\x1a&POGOProtos/Inventory/Item/ItemId.proto\"\x89\x03\n\x0cInventoryKey\x12\x12\n\npokemon_id\x18\x01 \x01(\x06\x12/\n\x04item\x18\x02 \x01(\x0e\x32!.POGOProtos.Inventory.Item.ItemId\x12\x18\n\x10pokedex_entry_id\x18\x03 \x01(\x05\x12\x14\n\x0cplayer_stats\x18\x04 \x01(\x08\x12\x17\n\x0fplayer_currency\x18\x05 \x01(\x08\x12\x15\n\rplayer_camera\x18\x06 \x01(\x08\x12\x1a\n\x12inventory_upgrades\x18\x07 \x01(\x08\x12\x15\n\rapplied_items\x18\x08 \x01(\x08\x12\x16\n\x0e\x65gg_incubators\x18\t \x01(\x08\x12<\n\x11pokemon_family_id\x18\n \x01(\x0e\x32!.POGOProtos.Enums.PokemonFamilyId\x12/\n\nquest_type\x18\x0b \x01(\x0e\x32\x1b.POGOProtos.Enums.QuestType\x12\x1a\n\x12\x61vatar_template_id\x18\x0c \x01(\tb\x06proto3')
  ,
  dependencies=[POGOProtos_dot_Enums_dot_QuestType__pb2.DESCRIPTOR,POGOProtos_dot_Enums_dot_PokemonFamilyId__pb2.DESCRIPTOR,POGOProtos_dot_Inventory_dot_Item_dot_ItemId__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_INVENTORYKEY = _descriptor.Descriptor(
  name='InventoryKey',
  full_name='POGOProtos.Inventory.InventoryKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pokemon_id', full_name='POGOProtos.Inventory.InventoryKey.pokemon_id', index=0,
      number=1, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item', full_name='POGOProtos.Inventory.InventoryKey.item', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pokedex_entry_id', full_name='POGOProtos.Inventory.InventoryKey.pokedex_entry_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_stats', full_name='POGOProtos.Inventory.InventoryKey.player_stats', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_currency', full_name='POGOProtos.Inventory.InventoryKey.player_currency', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_camera', full_name='POGOProtos.Inventory.InventoryKey.player_camera', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inventory_upgrades', full_name='POGOProtos.Inventory.InventoryKey.inventory_upgrades', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='applied_items', full_name='POGOProtos.Inventory.InventoryKey.applied_items', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='egg_incubators', full_name='POGOProtos.Inventory.InventoryKey.egg_incubators', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pokemon_family_id', full_name='POGOProtos.Inventory.InventoryKey.pokemon_family_id', index=9,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quest_type', full_name='POGOProtos.Inventory.InventoryKey.quest_type', index=10,
      number=11, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avatar_template_id', full_name='POGOProtos.Inventory.InventoryKey.avatar_template_id', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=573,
)

_INVENTORYKEY.fields_by_name['item'].enum_type = POGOProtos_dot_Inventory_dot_Item_dot_ItemId__pb2._ITEMID
_INVENTORYKEY.fields_by_name['pokemon_family_id'].enum_type = POGOProtos_dot_Enums_dot_PokemonFamilyId__pb2._POKEMONFAMILYID
_INVENTORYKEY.fields_by_name['quest_type'].enum_type = POGOProtos_dot_Enums_dot_QuestType__pb2._QUESTTYPE
DESCRIPTOR.message_types_by_name['InventoryKey'] = _INVENTORYKEY

InventoryKey = _reflection.GeneratedProtocolMessageType('InventoryKey', (_message.Message,), dict(
  DESCRIPTOR = _INVENTORYKEY,
  __module__ = 'POGOProtos.Inventory.InventoryKey_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Inventory.InventoryKey)
  ))
_sym_db.RegisterMessage(InventoryKey)


# @@protoc_insertion_point(module_scope)
