# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/Pokemon/EvolutionBranch.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from POGOProtos.Enums import PokemonId_pb2 as POGOProtos_dot_Enums_dot_PokemonId__pb2
from POGOProtos.Inventory.Item import ItemId_pb2 as POGOProtos_dot_Inventory_dot_Item_dot_ItemId__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Settings/Master/Pokemon/EvolutionBranch.proto',
  package='POGOProtos.Settings.Master.Pokemon',
  syntax='proto3',
  serialized_pb=_b('\n8POGOProtos/Settings/Master/Pokemon/EvolutionBranch.proto\x12\"POGOProtos.Settings.Master.Pokemon\x1a POGOProtos/Enums/PokemonId.proto\x1a&POGOProtos/Inventory/Item/ItemId.proto\"\x9c\x01\n\x0f\x45volutionBranch\x12.\n\tevolution\x18\x01 \x01(\x0e\x32\x1b.POGOProtos.Enums.PokemonId\x12\x45\n\x1a\x65volution_item_requirement\x18\x02 \x01(\x0e\x32!.POGOProtos.Inventory.Item.ItemId\x12\x12\n\ncandy_cost\x18\x03 \x01(\x05\x62\x06proto3')
  ,
  dependencies=[POGOProtos_dot_Enums_dot_PokemonId__pb2.DESCRIPTOR,POGOProtos_dot_Inventory_dot_Item_dot_ItemId__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EVOLUTIONBRANCH = _descriptor.Descriptor(
  name='EvolutionBranch',
  full_name='POGOProtos.Settings.Master.Pokemon.EvolutionBranch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='evolution', full_name='POGOProtos.Settings.Master.Pokemon.EvolutionBranch.evolution', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='evolution_item_requirement', full_name='POGOProtos.Settings.Master.Pokemon.EvolutionBranch.evolution_item_requirement', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='candy_cost', full_name='POGOProtos.Settings.Master.Pokemon.EvolutionBranch.candy_cost', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=327,
)

_EVOLUTIONBRANCH.fields_by_name['evolution'].enum_type = POGOProtos_dot_Enums_dot_PokemonId__pb2._POKEMONID
_EVOLUTIONBRANCH.fields_by_name['evolution_item_requirement'].enum_type = POGOProtos_dot_Inventory_dot_Item_dot_ItemId__pb2._ITEMID
DESCRIPTOR.message_types_by_name['EvolutionBranch'] = _EVOLUTIONBRANCH

EvolutionBranch = _reflection.GeneratedProtocolMessageType('EvolutionBranch', (_message.Message,), dict(
  DESCRIPTOR = _EVOLUTIONBRANCH,
  __module__ = 'POGOProtos.Settings.Master.Pokemon.EvolutionBranch_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Settings.Master.Pokemon.EvolutionBranch)
  ))
_sym_db.RegisterMessage(EvolutionBranch)


# @@protoc_insertion_point(module_scope)
