# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/Pokemon/PokemonGenderSettings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Settings/Master/Pokemon/PokemonGenderSettings.proto',
  package='POGOProtos.Settings.Master.Pokemon',
  syntax='proto3',
  serialized_pb=_b('\n>POGOProtos/Settings/Master/Pokemon/PokemonGenderSettings.proto\x12\"POGOProtos.Settings.Master.Pokemon\"a\n\x15PokemonGenderSettings\x12\x14\n\x0cmale_percent\x18\x01 \x01(\x02\x12\x16\n\x0e\x66\x65male_percent\x18\x02 \x01(\x02\x12\x1a\n\x12genderless_percent\x18\x03 \x01(\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_POKEMONGENDERSETTINGS = _descriptor.Descriptor(
  name='PokemonGenderSettings',
  full_name='POGOProtos.Settings.Master.Pokemon.PokemonGenderSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='male_percent', full_name='POGOProtos.Settings.Master.Pokemon.PokemonGenderSettings.male_percent', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='female_percent', full_name='POGOProtos.Settings.Master.Pokemon.PokemonGenderSettings.female_percent', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='genderless_percent', full_name='POGOProtos.Settings.Master.Pokemon.PokemonGenderSettings.genderless_percent', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=199,
)

DESCRIPTOR.message_types_by_name['PokemonGenderSettings'] = _POKEMONGENDERSETTINGS

PokemonGenderSettings = _reflection.GeneratedProtocolMessageType('PokemonGenderSettings', (_message.Message,), dict(
  DESCRIPTOR = _POKEMONGENDERSETTINGS,
  __module__ = 'POGOProtos.Settings.Master.Pokemon.PokemonGenderSettings_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Settings.Master.Pokemon.PokemonGenderSettings)
  ))
_sym_db.RegisterMessage(PokemonGenderSettings)


# @@protoc_insertion_point(module_scope)
