# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/FormSettings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from POGOProtos.Enums import Form_pb2 as POGOProtos_dot_Enums_dot_Form__pb2
from POGOProtos.Enums import PokemonId_pb2 as POGOProtos_dot_Enums_dot_PokemonId__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Settings/Master/FormSettings.proto',
  package='POGOProtos.Settings.Master',
  syntax='proto3',
  serialized_pb=_b('\n-POGOProtos/Settings/Master/FormSettings.proto\x12\x1aPOGOProtos.Settings.Master\x1a\x1bPOGOProtos/Enums/Form.proto\x1a POGOProtos/Enums/PokemonId.proto\"\xc4\x01\n\x0c\x46ormSettings\x12,\n\x07pokemon\x18\x01 \x01(\x0e\x32\x1b.POGOProtos.Enums.PokemonId\x12<\n\x05\x66orms\x18\x02 \x03(\x0b\x32-.POGOProtos.Settings.Master.FormSettings.Form\x1aH\n\x04\x46orm\x12$\n\x04\x66orm\x18\x01 \x01(\x0e\x32\x16.POGOProtos.Enums.Form\x12\x1a\n\x12\x61sset_bundle_value\x18\x02 \x01(\x05\x62\x06proto3')
  ,
  dependencies=[POGOProtos_dot_Enums_dot_Form__pb2.DESCRIPTOR,POGOProtos_dot_Enums_dot_PokemonId__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FORMSETTINGS_FORM = _descriptor.Descriptor(
  name='Form',
  full_name='POGOProtos.Settings.Master.FormSettings.Form',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='form', full_name='POGOProtos.Settings.Master.FormSettings.Form.form', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='asset_bundle_value', full_name='POGOProtos.Settings.Master.FormSettings.Form.asset_bundle_value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=337,
)

_FORMSETTINGS = _descriptor.Descriptor(
  name='FormSettings',
  full_name='POGOProtos.Settings.Master.FormSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pokemon', full_name='POGOProtos.Settings.Master.FormSettings.pokemon', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='forms', full_name='POGOProtos.Settings.Master.FormSettings.forms', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_FORMSETTINGS_FORM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=337,
)

_FORMSETTINGS_FORM.fields_by_name['form'].enum_type = POGOProtos_dot_Enums_dot_Form__pb2._FORM
_FORMSETTINGS_FORM.containing_type = _FORMSETTINGS
_FORMSETTINGS.fields_by_name['pokemon'].enum_type = POGOProtos_dot_Enums_dot_PokemonId__pb2._POKEMONID
_FORMSETTINGS.fields_by_name['forms'].message_type = _FORMSETTINGS_FORM
DESCRIPTOR.message_types_by_name['FormSettings'] = _FORMSETTINGS

FormSettings = _reflection.GeneratedProtocolMessageType('FormSettings', (_message.Message,), dict(

  Form = _reflection.GeneratedProtocolMessageType('Form', (_message.Message,), dict(
    DESCRIPTOR = _FORMSETTINGS_FORM,
    __module__ = 'POGOProtos.Settings.Master.FormSettings_pb2'
    # @@protoc_insertion_point(class_scope:POGOProtos.Settings.Master.FormSettings.Form)
    ))
  ,
  DESCRIPTOR = _FORMSETTINGS,
  __module__ = 'POGOProtos.Settings.Master.FormSettings_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Settings.Master.FormSettings)
  ))
_sym_db.RegisterMessage(FormSettings)
_sym_db.RegisterMessage(FormSettings.Form)


# @@protoc_insertion_point(module_scope)
