# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/GenderSettings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from POGOProtos.Enums import PokemonId_pb2 as POGOProtos_dot_Enums_dot_PokemonId__pb2
from POGOProtos.Settings.Master.Pokemon import PokemonGenderSettings_pb2 as POGOProtos_dot_Settings_dot_Master_dot_Pokemon_dot_PokemonGenderSettings__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Settings/Master/GenderSettings.proto',
  package='POGOProtos.Settings.Master',
  syntax='proto3',
  serialized_pb=_b('\n/POGOProtos/Settings/Master/GenderSettings.proto\x12\x1aPOGOProtos.Settings.Master\x1a POGOProtos/Enums/PokemonId.proto\x1a>POGOProtos/Settings/Master/Pokemon/PokemonGenderSettings.proto\"\x89\x01\n\x0eGenderSettings\x12,\n\x07pokemon\x18\x01 \x01(\x0e\x32\x1b.POGOProtos.Enums.PokemonId\x12I\n\x06gender\x18\x02 \x01(\x0b\x32\x39.POGOProtos.Settings.Master.Pokemon.PokemonGenderSettingsb\x06proto3')
  ,
  dependencies=[POGOProtos_dot_Enums_dot_PokemonId__pb2.DESCRIPTOR,POGOProtos_dot_Settings_dot_Master_dot_Pokemon_dot_PokemonGenderSettings__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GENDERSETTINGS = _descriptor.Descriptor(
  name='GenderSettings',
  full_name='POGOProtos.Settings.Master.GenderSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pokemon', full_name='POGOProtos.Settings.Master.GenderSettings.pokemon', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gender', full_name='POGOProtos.Settings.Master.GenderSettings.gender', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=315,
)

_GENDERSETTINGS.fields_by_name['pokemon'].enum_type = POGOProtos_dot_Enums_dot_PokemonId__pb2._POKEMONID
_GENDERSETTINGS.fields_by_name['gender'].message_type = POGOProtos_dot_Settings_dot_Master_dot_Pokemon_dot_PokemonGenderSettings__pb2._POKEMONGENDERSETTINGS
DESCRIPTOR.message_types_by_name['GenderSettings'] = _GENDERSETTINGS

GenderSettings = _reflection.GeneratedProtocolMessageType('GenderSettings', (_message.Message,), dict(
  DESCRIPTOR = _GENDERSETTINGS,
  __module__ = 'POGOProtos.Settings.Master.GenderSettings_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Settings.Master.GenderSettings)
  ))
_sym_db.RegisterMessage(GenderSettings)


# @@protoc_insertion_point(module_scope)
