# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/QuestSettings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from POGOProtos.Enums import QuestType_pb2 as POGOProtos_dot_Enums_dot_QuestType__pb2
from POGOProtos.Settings.Master.Quest import DailyQuestSettings_pb2 as POGOProtos_dot_Settings_dot_Master_dot_Quest_dot_DailyQuestSettings__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Settings/Master/QuestSettings.proto',
  package='POGOProtos.Settings.Master',
  syntax='proto3',
  serialized_pb=_b('\n.POGOProtos/Settings/Master/QuestSettings.proto\x12\x1aPOGOProtos.Settings.Master\x1a POGOProtos/Enums/QuestType.proto\x1a\x39POGOProtos/Settings/Master/Quest/DailyQuestSettings.proto\"\x8b\x01\n\rQuestSettings\x12/\n\nquest_type\x18\x01 \x01(\x0e\x32\x1b.POGOProtos.Enums.QuestType\x12I\n\x0b\x64\x61ily_quest\x18\x02 \x01(\x0b\x32\x34.POGOProtos.Settings.Master.Quest.DailyQuestSettingsb\x06proto3')
  ,
  dependencies=[POGOProtos_dot_Enums_dot_QuestType__pb2.DESCRIPTOR,POGOProtos_dot_Settings_dot_Master_dot_Quest_dot_DailyQuestSettings__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_QUESTSETTINGS = _descriptor.Descriptor(
  name='QuestSettings',
  full_name='POGOProtos.Settings.Master.QuestSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quest_type', full_name='POGOProtos.Settings.Master.QuestSettings.quest_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='daily_quest', full_name='POGOProtos.Settings.Master.QuestSettings.daily_quest', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=311,
)

_QUESTSETTINGS.fields_by_name['quest_type'].enum_type = POGOProtos_dot_Enums_dot_QuestType__pb2._QUESTTYPE
_QUESTSETTINGS.fields_by_name['daily_quest'].message_type = POGOProtos_dot_Settings_dot_Master_dot_Quest_dot_DailyQuestSettings__pb2._DAILYQUESTSETTINGS
DESCRIPTOR.message_types_by_name['QuestSettings'] = _QUESTSETTINGS

QuestSettings = _reflection.GeneratedProtocolMessageType('QuestSettings', (_message.Message,), dict(
  DESCRIPTOR = _QUESTSETTINGS,
  __module__ = 'POGOProtos.Settings.Master.QuestSettings_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Settings.Master.QuestSettings)
  ))
_sym_db.RegisterMessage(QuestSettings)


# @@protoc_insertion_point(module_scope)
