# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/SetAvatarItemAsViewedResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Networking/Responses/SetAvatarItemAsViewedResponse.proto',
  package='POGOProtos.Networking.Responses',
  syntax='proto3',
  serialized_pb=_b('\nCPOGOProtos/Networking/Responses/SetAvatarItemAsViewedResponse.proto\x12\x1fPOGOProtos.Networking.Responses\"\xa5\x01\n\x1dSetAvatarItemAsViewedResponse\x12U\n\x06result\x18\x01 \x01(\x0e\x32\x45.POGOProtos.Networking.Responses.SetAvatarItemAsViewedResponse.Result\"-\n\x06Result\x12\t\n\x05UNSET\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0b\n\x07\x46\x41ILURE\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SETAVATARITEMASVIEWEDRESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='POGOProtos.Networking.Responses.SetAvatarItemAsViewedResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILURE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=225,
  serialized_end=270,
)
_sym_db.RegisterEnumDescriptor(_SETAVATARITEMASVIEWEDRESPONSE_RESULT)


_SETAVATARITEMASVIEWEDRESPONSE = _descriptor.Descriptor(
  name='SetAvatarItemAsViewedResponse',
  full_name='POGOProtos.Networking.Responses.SetAvatarItemAsViewedResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='POGOProtos.Networking.Responses.SetAvatarItemAsViewedResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SETAVATARITEMASVIEWEDRESPONSE_RESULT,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=270,
)

_SETAVATARITEMASVIEWEDRESPONSE.fields_by_name['result'].enum_type = _SETAVATARITEMASVIEWEDRESPONSE_RESULT
_SETAVATARITEMASVIEWEDRESPONSE_RESULT.containing_type = _SETAVATARITEMASVIEWEDRESPONSE
DESCRIPTOR.message_types_by_name['SetAvatarItemAsViewedResponse'] = _SETAVATARITEMASVIEWEDRESPONSE

SetAvatarItemAsViewedResponse = _reflection.GeneratedProtocolMessageType('SetAvatarItemAsViewedResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETAVATARITEMASVIEWEDRESPONSE,
  __module__ = 'POGOProtos.Networking.Responses.SetAvatarItemAsViewedResponse_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Responses.SetAvatarItemAsViewedResponse)
  ))
_sym_db.RegisterMessage(SetAvatarItemAsViewedResponse)


# @@protoc_insertion_point(module_scope)
