# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/UseItemEncounterResponse.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from POGOProtos.Data.Capture import CaptureProbability_pb2 as POGOProtos_dot_Data_dot_Capture_dot_CaptureProbability__pb2
from POGOProtos.Inventory.Item import ItemId_pb2 as POGOProtos_dot_Inventory_dot_Item_dot_ItemId__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Networking/Responses/UseItemEncounterResponse.proto',
  package='POGOProtos.Networking.Responses',
  syntax='proto3',
  serialized_pb=_b('\n>POGOProtos/Networking/Responses/UseItemEncounterResponse.proto\x12\x1fPOGOProtos.Networking.Responses\x1a\x30POGOProtos/Data/Capture/CaptureProbability.proto\x1a&POGOProtos/Inventory/Item/ItemId.proto\"\xe9\x02\n\x18UseItemEncounterResponse\x12P\n\x06status\x18\x01 \x01(\x0e\x32@.POGOProtos.Networking.Responses.UseItemEncounterResponse.Status\x12H\n\x13\x63\x61pture_probability\x18\x02 \x01(\x0b\x32+.POGOProtos.Data.Capture.CaptureProbability\x12\x36\n\x0b\x61\x63tive_item\x18\x03 \x01(\x0e\x32!.POGOProtos.Inventory.Item.ItemId\"y\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x15\n\x11\x41LREADY_COMPLETED\x10\x01\x12\x16\n\x12\x41\x43TIVE_ITEM_EXISTS\x10\x02\x12\x18\n\x14NO_ITEM_IN_INVENTORY\x10\x03\x12\x19\n\x15INVALID_ITEM_CATEGORY\x10\x04\x62\x06proto3')
  ,
  dependencies=[POGOProtos_dot_Data_dot_Capture_dot_CaptureProbability__pb2.DESCRIPTOR,POGOProtos_dot_Inventory_dot_Item_dot_ItemId__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_USEITEMENCOUNTERRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='POGOProtos.Networking.Responses.UseItemEncounterResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALREADY_COMPLETED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVE_ITEM_EXISTS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_ITEM_IN_INVENTORY', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_ITEM_CATEGORY', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=430,
  serialized_end=551,
)
_sym_db.RegisterEnumDescriptor(_USEITEMENCOUNTERRESPONSE_STATUS)


_USEITEMENCOUNTERRESPONSE = _descriptor.Descriptor(
  name='UseItemEncounterResponse',
  full_name='POGOProtos.Networking.Responses.UseItemEncounterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='POGOProtos.Networking.Responses.UseItemEncounterResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='capture_probability', full_name='POGOProtos.Networking.Responses.UseItemEncounterResponse.capture_probability', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='active_item', full_name='POGOProtos.Networking.Responses.UseItemEncounterResponse.active_item', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _USEITEMENCOUNTERRESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=551,
)

_USEITEMENCOUNTERRESPONSE.fields_by_name['status'].enum_type = _USEITEMENCOUNTERRESPONSE_STATUS
_USEITEMENCOUNTERRESPONSE.fields_by_name['capture_probability'].message_type = POGOProtos_dot_Data_dot_Capture_dot_CaptureProbability__pb2._CAPTUREPROBABILITY
_USEITEMENCOUNTERRESPONSE.fields_by_name['active_item'].enum_type = POGOProtos_dot_Inventory_dot_Item_dot_ItemId__pb2._ITEMID
_USEITEMENCOUNTERRESPONSE_STATUS.containing_type = _USEITEMENCOUNTERRESPONSE
DESCRIPTOR.message_types_by_name['UseItemEncounterResponse'] = _USEITEMENCOUNTERRESPONSE

UseItemEncounterResponse = _reflection.GeneratedProtocolMessageType('UseItemEncounterResponse', (_message.Message,), dict(
  DESCRIPTOR = _USEITEMENCOUNTERRESPONSE,
  __module__ = 'POGOProtos.Networking.Responses.UseItemEncounterResponse_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Responses.UseItemEncounterResponse)
  ))
_sym_db.RegisterMessage(UseItemEncounterResponse)


# @@protoc_insertion_point(module_scope)
