# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Quests/DailyQuest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Data/Quests/DailyQuest.proto',
  package='POGOProtos.Data.Quests',
  syntax='proto3',
  serialized_pb=_b('\n\'POGOProtos/Data/Quests/DailyQuest.proto\x12\x16POGOProtos.Data.Quests\"I\n\nDailyQuest\x12\x1d\n\x15\x63urrent_period_bucket\x18\x01 \x01(\x05\x12\x1c\n\x14\x63urrent_streak_count\x18\x02 \x01(\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DAILYQUEST = _descriptor.Descriptor(
  name='DailyQuest',
  full_name='POGOProtos.Data.Quests.DailyQuest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_period_bucket', full_name='POGOProtos.Data.Quests.DailyQuest.current_period_bucket', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='current_streak_count', full_name='POGOProtos.Data.Quests.DailyQuest.current_streak_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=140,
)

DESCRIPTOR.message_types_by_name['DailyQuest'] = _DAILYQUEST

DailyQuest = _reflection.GeneratedProtocolMessageType('DailyQuest', (_message.Message,), dict(
  DESCRIPTOR = _DAILYQUEST,
  __module__ = 'POGOProtos.Data.Quests.DailyQuest_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Data.Quests.DailyQuest)
  ))
_sym_db.RegisterMessage(DailyQuest)


# @@protoc_insertion_point(module_scope)
