# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Quests/Quest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from POGOProtos.Enums import QuestType_pb2 as POGOProtos_dot_Enums_dot_QuestType__pb2
from POGOProtos.Data.Quests import DailyQuest_pb2 as POGOProtos_dot_Data_dot_Quests_dot_DailyQuest__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Data/Quests/Quest.proto',
  package='POGOProtos.Data.Quests',
  syntax='proto3',
  serialized_pb=_b('\n\"POGOProtos/Data/Quests/Quest.proto\x12\x16POGOProtos.Data.Quests\x1a POGOProtos/Enums/QuestType.proto\x1a\'POGOProtos/Data/Quests/DailyQuest.proto\"q\n\x05Quest\x12/\n\nquest_type\x18\x01 \x01(\x0e\x32\x1b.POGOProtos.Enums.QuestType\x12\x37\n\x0b\x64\x61ily_quest\x18\x02 \x01(\x0b\x32\".POGOProtos.Data.Quests.DailyQuestb\x06proto3')
  ,
  dependencies=[POGOProtos_dot_Enums_dot_QuestType__pb2.DESCRIPTOR,POGOProtos_dot_Data_dot_Quests_dot_DailyQuest__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_QUEST = _descriptor.Descriptor(
  name='Quest',
  full_name='POGOProtos.Data.Quests.Quest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quest_type', full_name='POGOProtos.Data.Quests.Quest.quest_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='daily_quest', full_name='POGOProtos.Data.Quests.Quest.daily_quest', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=250,
)

_QUEST.fields_by_name['quest_type'].enum_type = POGOProtos_dot_Enums_dot_QuestType__pb2._QUESTTYPE
_QUEST.fields_by_name['daily_quest'].message_type = POGOProtos_dot_Data_dot_Quests_dot_DailyQuest__pb2._DAILYQUEST
DESCRIPTOR.message_types_by_name['Quest'] = _QUEST

Quest = _reflection.GeneratedProtocolMessageType('Quest', (_message.Message,), dict(
  DESCRIPTOR = _QUEST,
  __module__ = 'POGOProtos.Data.Quests.Quest_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Data.Quests.Quest)
  ))
_sym_db.RegisterMessage(Quest)


# @@protoc_insertion_point(module_scope)
