# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/ListAvatarCustomizationsMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from POGOProtos.Data.Player import PlayerAvatarType_pb2 as POGOProtos_dot_Data_dot_Player_dot_PlayerAvatarType__pb2
from POGOProtos.Enums import Slot_pb2 as POGOProtos_dot_Enums_dot_Slot__pb2
from POGOProtos.Enums import Filter_pb2 as POGOProtos_dot_Enums_dot_Filter__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Networking/Requests/Messages/ListAvatarCustomizationsMessage.proto',
  package='POGOProtos.Networking.Requests.Messages',
  syntax='proto3',
  serialized_pb=_b('\nMPOGOProtos/Networking/Requests/Messages/ListAvatarCustomizationsMessage.proto\x12\'POGOProtos.Networking.Requests.Messages\x1a-POGOProtos/Data/Player/PlayerAvatarType.proto\x1a\x1bPOGOProtos/Enums/Slot.proto\x1a\x1dPOGOProtos/Enums/Filter.proto\"\xcf\x01\n\x1fListAvatarCustomizationsMessage\x12=\n\x0b\x61vatar_type\x18\x01 \x01(\x0e\x32(.POGOProtos.Data.Player.PlayerAvatarType\x12$\n\x04slot\x18\x02 \x03(\x0e\x32\x16.POGOProtos.Enums.Slot\x12)\n\x07\x66ilters\x18\x03 \x03(\x0e\x32\x18.POGOProtos.Enums.Filter\x12\r\n\x05start\x18\x04 \x01(\x05\x12\r\n\x05limit\x18\x05 \x01(\x05\x62\x06proto3')
  ,
  dependencies=[POGOProtos_dot_Data_dot_Player_dot_PlayerAvatarType__pb2.DESCRIPTOR,POGOProtos_dot_Enums_dot_Slot__pb2.DESCRIPTOR,POGOProtos_dot_Enums_dot_Filter__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LISTAVATARCUSTOMIZATIONSMESSAGE = _descriptor.Descriptor(
  name='ListAvatarCustomizationsMessage',
  full_name='POGOProtos.Networking.Requests.Messages.ListAvatarCustomizationsMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='avatar_type', full_name='POGOProtos.Networking.Requests.Messages.ListAvatarCustomizationsMessage.avatar_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='slot', full_name='POGOProtos.Networking.Requests.Messages.ListAvatarCustomizationsMessage.slot', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filters', full_name='POGOProtos.Networking.Requests.Messages.ListAvatarCustomizationsMessage.filters', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start', full_name='POGOProtos.Networking.Requests.Messages.ListAvatarCustomizationsMessage.start', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit', full_name='POGOProtos.Networking.Requests.Messages.ListAvatarCustomizationsMessage.limit', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=437,
)

_LISTAVATARCUSTOMIZATIONSMESSAGE.fields_by_name['avatar_type'].enum_type = POGOProtos_dot_Data_dot_Player_dot_PlayerAvatarType__pb2._PLAYERAVATARTYPE
_LISTAVATARCUSTOMIZATIONSMESSAGE.fields_by_name['slot'].enum_type = POGOProtos_dot_Enums_dot_Slot__pb2._SLOT
_LISTAVATARCUSTOMIZATIONSMESSAGE.fields_by_name['filters'].enum_type = POGOProtos_dot_Enums_dot_Filter__pb2._FILTER
DESCRIPTOR.message_types_by_name['ListAvatarCustomizationsMessage'] = _LISTAVATARCUSTOMIZATIONSMESSAGE

ListAvatarCustomizationsMessage = _reflection.GeneratedProtocolMessageType('ListAvatarCustomizationsMessage', (_message.Message,), dict(
  DESCRIPTOR = _LISTAVATARCUSTOMIZATIONSMESSAGE,
  __module__ = 'POGOProtos.Networking.Requests.Messages.ListAvatarCustomizationsMessage_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Requests.Messages.ListAvatarCustomizationsMessage)
  ))
_sym_db.RegisterMessage(ListAvatarCustomizationsMessage)


# @@protoc_insertion_point(module_scope)
