# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/SetAvatarItemAsViewedMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='POGOProtos/Networking/Requests/Messages/SetAvatarItemAsViewedMessage.proto',
  package='POGOProtos.Networking.Requests.Messages',
  syntax='proto3',
  serialized_pb=_b('\nJPOGOProtos/Networking/Requests/Messages/SetAvatarItemAsViewedMessage.proto\x12\'POGOProtos.Networking.Requests.Messages\":\n\x1cSetAvatarItemAsViewedMessage\x12\x1a\n\x12\x61vatar_template_id\x18\x01 \x03(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SETAVATARITEMASVIEWEDMESSAGE = _descriptor.Descriptor(
  name='SetAvatarItemAsViewedMessage',
  full_name='POGOProtos.Networking.Requests.Messages.SetAvatarItemAsViewedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='avatar_template_id', full_name='POGOProtos.Networking.Requests.Messages.SetAvatarItemAsViewedMessage.avatar_template_id', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=177,
)

DESCRIPTOR.message_types_by_name['SetAvatarItemAsViewedMessage'] = _SETAVATARITEMASVIEWEDMESSAGE

SetAvatarItemAsViewedMessage = _reflection.GeneratedProtocolMessageType('SetAvatarItemAsViewedMessage', (_message.Message,), dict(
  DESCRIPTOR = _SETAVATARITEMASVIEWEDMESSAGE,
  __module__ = 'POGOProtos.Networking.Requests.Messages.SetAvatarItemAsViewedMessage_pb2'
  # @@protoc_insertion_point(class_scope:POGOProtos.Networking.Requests.Messages.SetAvatarItemAsViewedMessage)
  ))
_sym_db.RegisterMessage(SetAvatarItemAsViewedMessage)


# @@protoc_insertion_point(module_scope)
